
FROM rabbitmq:4-alpine
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY definitions.json /etc/rabbitmq/definitions.json
RUN rabbitmq-plugins enable --offline rabbitmq_management
EXPOSE 5672 15672
